export const pallete = {
  white: '#FFFFFF',
  black: '#000000',

  primaryWhite: '#FFFFFF',
  primaryBlack: '#01080a',

  deepRed: '#FF0000',
  darkRed: '#942020',
  deepPurple: '#7B35DA',
  lowDeepPurple: '#rgba(143, 60, 237, 0.8)',
  lowOpacityBlack: 'rgba(0, 0, 0, 0.5)',
  purple: '#270B53',
  fadedPurple: 'rgba(39, 11, 83, 0.47)',
  darkPurple: '#230F69',
  midPurple: '#F1E8FF',
  lightPurple: '#F5F2FF',
  blue: '#124E78',
  orange: '#FE5F55',
  lightRed: '#FCCCCC',
  lightRed2: '#F97066',
  lightPink: '#F5F2FFDE',
  black1: '#202020',
  grey1: '#e3e3e3',
  grey2: '#424242',
  grey3: '#475467',
  grey4: '#47546799',
  grey5: 'rgba(27, 27, 27, 0.34)',
  purpleGrey: '#9589A8',
  purple1: '#5619B8',
  purple2: '#8754FE',
  green: '#027A48',
  green2: '#2AC686',
  red: '#E95050',
  lightGreen: '#D1FADF',
  yellow: '#FFA224',
  yellow2: '#FFA224',
  lightYellow: '#FCEFD8',
  deepYellow: '#914421',
  magnolia: '#FAF8FF',
  cosmos: '#FFD8D6',
  brick: '#B42318',
  fog: '#e4d4ff',
  lotion: '#fafafa',
  independence: 'rgba(71, 84, 103, 0.6)',
} as const;
export type PalleteColors = keyof typeof pallete;

export const Colors = {
  ...pallete,
  backgroundWhite: pallete.primaryWhite,
  backgroundBlack: pallete.primaryBlack,

  seperator: pallete.primaryBlack,

  textInput: {
    light: {
      main: pallete.primaryWhite,
    },
    dark: {
      main: pallete.primaryWhite,
    },
  },

  texts: {
    light: {
      black: pallete.primaryBlack,
      white: pallete.white,
      deepPurple: pallete.deepPurple,
      darkPurple: pallete.darkPurple,
      purple: pallete.purple,
      grey3: pallete.grey3,
      grey2: pallete.grey2,
      darkRed: pallete.darkRed,
      purpleGrey: pallete.purpleGrey,
      purple1: pallete.purple1,

      grey4: pallete.grey4,
      green: pallete.green,
      lightGreen: pallete.lightGreen,
      yellow: pallete.yellow,
      deepYellow: pallete.deepYellow,

      magnolia: pallete.magnolia,
      cosmos: pallete.cosmos,
      brick: pallete.brick,
      fog: pallete.fog,
      fadedPurple: pallete.fadedPurple,
      deepRed: pallete.deepRed,
    },

    dark: {
      black: pallete.primaryBlack,
      white: pallete.white,
      deepPurple: pallete.deepPurple,
      purple: pallete.purple,
      darkPurple: pallete.darkPurple,
      grey3: pallete.grey3,
      grey2: pallete.grey2,

      darkRed: pallete.darkRed,
      purpleGrey: pallete.purpleGrey,
      purple1: pallete.purple1,

      grey4: pallete.grey4,
      green: pallete.green,
      lightGreen: pallete.lightGreen,
      yellow: pallete.yellow,
      deepYellow: pallete.deepYellow,

      magnolia: pallete.magnolia,
      cosmos: pallete.cosmos,
      brick: pallete.brick,
      fog: pallete.fog,
      fadedPurple: pallete.fadedPurple,
      deepRed: pallete.deepRed,
    },
  },

  buttons: {
    light: {
      primary: pallete.deepPurple,
      secondary: pallete.primaryWhite,
      success: pallete.primaryWhite,
      danger: pallete.primaryWhite,
      magnolia: pallete.magnolia,
      cosmos: pallete.cosmos,
      brick: pallete.brick,
      fog: pallete.fog,
      purple: pallete.purple,
    },
    dark: {
      primary: pallete.deepPurple,
      secondary: pallete.primaryBlack,
      success: pallete.primaryBlack,
      danger: pallete.primaryBlack,
      magnolia: pallete.magnolia,
      cosmos: pallete.cosmos,
      brick: pallete.brick,
      fog: pallete.fog,
      purple: pallete.purple,
    },
  },
};
